# Generated by Django 5.2.17 on 2026-09-29 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên sự kiện")),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                ("location", models.CharField(max_length=200, verbose_name="Địa điểm")),
                ("starts_at", models.DateTimeField(verbose_name="Thời gian diễn ra")),
                ("register_deadline", models.DateTimeField(verbose_name="Hạn đăng ký")),
                (
                    "capacity",
                    models.PositiveIntegerField(default=100, verbose_name="Sức chứa"),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/",
                        verbose_name="Ảnh bìa",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Đang chuẩn bị"),
                            ("OPEN", "Mở đăng ký"),
                            ("CLOSED", "Đóng đăng ký"),
                            ("DONE", "Đã diễn ra"),
                            ("CANCELLED", "Đã huỷ"),
                        ],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sự kiện",
                "verbose_name_plural": "Sự kiện",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên loại vé")),
                (
                    "price",
                    models.PositiveIntegerField(default=0, verbose_name="Giá (VNĐ)"),
                ),
                (
                    "quota",
                    models.PositiveIntegerField(default=50, verbose_name="Số lượng"),
                ),
                ("sold", models.PositiveIntegerField(default=0, verbose_name="Đã bán")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="events.event",
                        verbose_name="Sự kiện",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loại vé",
                "verbose_name_plural": "Loại vé",
                "ordering": ["price", "id"],
            },
        ),
    ]
