# Generated by Django 5.2.17 on 2026-09-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='Để 0 nếu chưa lập ngân sách.', verbose_name='Ngân sách dự kiến (VNĐ)'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('MUSIC', 'Âm nhạc'), ('ACADEMIC', 'Học thuật'), ('VOLUNTEER', 'Thiện nguyện'), ('SPORT', 'Thể thao'), ('SOCIAL', 'Giao lưu'), ('OTHER', 'Khác')], db_index=True, default='OTHER', max_length=10, verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Đã nhắc lịch lúc'),
        ),
    ]
