# Generated by Django 5.2.17 on 2026-10-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_budget_event_category_event_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='require_id_check',
            field=models.BooleanField(default=False, help_text='Nên bật cho show đông, dễ bị phe vé. Người tham gia phải mang thẻ sinh viên hoặc CCCD trùng tên trên vé.', verbose_name='Vé ghi danh - đối chiếu giấy tờ khi check-in'),
        ),
    ]
