# Generated by Django 5.2.17 on 2026-10-02 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizing', '0004_department_and_task_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tên đợt tuyển')),
                ('description', models.TextField(blank=True, help_text='Yêu cầu, lịch casting/phỏng vấn, quyền lợi… Hiện trên trang Tuyển thành viên.', verbose_name='Thông tin đợt tuyển')),
                ('opens_at', models.DateTimeField(verbose_name='Mở nhận đơn')),
                ('closes_at', models.DateTimeField(verbose_name='Hạn nộp đơn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, help_text='Để trống = mọi Ban đều nhận.', related_name='recruitment_rounds', to='organizing.department', verbose_name='Ban nhận đơn')),
            ],
            options={
                'verbose_name': 'Đợt tuyển',
                'verbose_name_plural': 'Đợt tuyển',
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.CharField(help_text='Vd: Guitar đệm hát, Vocal; hoặc Thiết kế, Chụp ảnh, Dẫn chương trình', max_length=200, verbose_name='Nhạc cụ / thế mạnh')),
                ('level', models.CharField(choices=[('NEW', 'Mới bắt đầu, muốn được học'), ('BASIC', 'Biết cơ bản'), ('GOOD', 'Khá, đã tập lâu'), ('STAGE', 'Đã từng biểu diễn / làm sản phẩm')], default='BASIC', max_length=6, verbose_name='Trình độ')),
                ('portfolio_url', models.URLField(blank=True, help_text='Không bắt buộc: video cover, SoundCloud, Behance, Drive…', verbose_name='Link video / sản phẩm')),
                ('motivation', models.TextField(max_length=1000, verbose_name='Vì sao bạn muốn tham gia?')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('INTERVIEW', 'Hẹn casting / phỏng vấn'), ('ACCEPTED', 'Đã nhận'), ('REJECTED', 'Chưa phù hợp'), ('WITHDRAWN', 'Đã rút đơn')], db_index=True, default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('interview_at', models.DateTimeField(blank=True, null=True, verbose_name='Lịch casting / phỏng vấn')),
                ('review_note', models.CharField(blank=True, help_text='Ứng viên sẽ đọc được: địa điểm casting, cần chuẩn bị gì…', max_length=255, verbose_name='Lời nhắn cho ứng viên')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Duyệt lúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Nộp lúc')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='organizing.department', verbose_name='Ban mong muốn')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Ứng viên')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.recruitmentround', verbose_name='Đợt tuyển')),
            ],
            options={
                'verbose_name': 'Đơn ứng tuyển',
                'verbose_name_plural': 'Đơn ứng tuyển',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('round', 'user'), name='uniq_application_per_round')],
            },
        ),
    ]
