# Generated by Django 5.2.17 on 2026-09-29 03:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "positive",
                    models.TextField(blank=True, verbose_name="Điểm được khen"),
                ),
                (
                    "negative",
                    models.TextField(blank=True, verbose_name="Điểm bị góp ý"),
                ),
                (
                    "suggestion",
                    models.TextField(blank=True, verbose_name="Đề xuất cải thiện"),
                ),
                (
                    "feedback_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số phản hồi đã tóm tắt"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Tạo lúc"),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_summary",
                        to="events.event",
                        verbose_name="Sự kiện",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tóm tắt phản hồi (AI)",
                "verbose_name_plural": "Tóm tắt phản hồi (AI)",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Số sao",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Góp ý")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày gửi"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="events.event",
                        verbose_name="Sự kiện",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người gửi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phản hồi",
                "verbose_name_plural": "Phản hồi",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "user"), name="unique_feedback_per_user_event"
                    )
                ],
            },
        ),
    ]
