# Generated by Django 5.2.17 on 2026-10-02 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizing', '0004_department_and_task_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Họ tên')),
                ('position', models.CharField(help_text='Vd: Chủ nhiệm, Phó chủ nhiệm, Trưởng ban Chuyên môn', max_length=80, verbose_name='Chức vụ')),
                ('term', models.CharField(default='2026 - 2027', max_length=20, verbose_name='Nhiệm kỳ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='officers/', verbose_name='Ảnh')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_current', models.BooleanField(default=True, verbose_name='Đương nhiệm')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='organizing.department', verbose_name='Ban phụ trách')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Thành viên Ban Quản trị',
                'verbose_name_plural': 'Ban Quản trị',
                'ordering': ['order', 'id'],
            },
        ),
    ]
