# Generated by Django 5.2.17 on 2026-10-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_uniq_user_email_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GUEST', 'Khách'), ('MEMBER', 'Thành viên'), ('STAFF', 'Thành viên BTC'), ('LEAD', 'Trưởng BTC'), ('ADMIN', 'Admin')], default='GUEST', max_length=10, verbose_name='Vai trò'),
        ),
    ]
