# Generated by Django 5.2.17 on 2026-10-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(choices=[('KMA', 'Sinh viên Học viện Kỹ thuật Mật mã'), ('OTHER', 'Sinh viên trường khác'), ('PUBLIC', 'Không phải sinh viên')], default='KMA', max_length=6, verbose_name='Đối tượng'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=120, verbose_name='Trường / đơn vị'),
        ),
    ]
