# Generated by Django 5.2.17 on 2026-10-02 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def grandfather_existing_users(apps, schema_editor):
    """
    Tài khoản tạo TRƯỚC khi có OTP coi như đã xác minh, để không bắt cả
    người dùng cũ phải nhập mã mới đặt được vé. Chỉ áp dụng tài khoản có email.
    """
    User = apps.get_model("accounts", "User")
    User.objects.exclude(email="").update(email_verified_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_affiliation_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Xác minh email lúc'),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, verbose_name='Mã (đã băm)')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Số lần nhập sai')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Gửi lúc')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Dùng lúc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Mã OTP email',
                'verbose_name_plural': 'Mã OTP email',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(grandfather_existing_users, migrations.RunPython.noop),
    ]
