# Generated by Django 5.2.17 on 2026-10-02 11:43

from django.db import migrations, models

from accounts.models import canonical_email


def fill_canonical(apps, schema_editor):
    """Điền email dạng chuẩn cho các tài khoản đã có."""
    User = apps.get_model("accounts", "User")
    users = list(User.objects.only("id", "email"))
    for u in users:
        u.email_canonical = canonical_email(u.email)
    User.objects.bulk_update(users, ["email_canonical"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_canonical',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=254, verbose_name='Email dạng chuẩn'),
        ),
        migrations.RunPython(fill_canonical, migrations.RunPython.noop),
    ]
