# Generated by Django 5.2.17 on 2026-09-29 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Tên công việc"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deadline"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "Chưa làm"),
                            ("DOING", "Đang làm"),
                            ("DONE", "Xong"),
                        ],
                        default="TODO",
                        max_length=6,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ghi chú tiến độ"
                    ),
                ),
                (
                    "created_by_ai",
                    models.BooleanField(default=False, verbose_name="Do AI gợi ý"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hoàn thành lúc"
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người phụ trách",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="events.event",
                        verbose_name="Sự kiện",
                    ),
                ),
            ],
            options={
                "verbose_name": "Công việc",
                "verbose_name_plural": "Công việc",
                "ordering": ["deadline", "id"],
            },
        ),
    ]
