# Generated by Django 5.2.17 on 2026-09-30 03:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_budget_event_category_event_ends_at_and_more'),
        ('organizing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Khoản chi')),
                ('category', models.CharField(choices=[('VENUE', 'Địa điểm'), ('EQUIP', 'Âm thanh - thiết bị'), ('PRINT', 'In ấn - truyền thông'), ('FOOD', 'Ăn uống'), ('GIFT', 'Quà tặng'), ('TRANS', 'Di chuyển'), ('OTHER', 'Khác')], default='OTHER', max_length=6, verbose_name='Hạng mục')),
                ('amount', models.PositiveIntegerField(verbose_name='Số tiền (VNĐ)')),
                ('spent_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày chi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Ảnh hoá đơn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người ghi')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='events.event', verbose_name='Sự kiện')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_paid', to=settings.AUTH_USER_MODEL, verbose_name='Người chi')),
            ],
            options={
                'verbose_name': 'Khoản chi',
                'verbose_name_plural': 'Khoản chi',
                'ordering': ['-spent_on', '-id'],
            },
        ),
    ]
