# Generated by Django 5.2.17 on 2026-09-30 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_budget_event_category_event_ends_at_and_more'),
        ('organizing', '0002_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Người giao'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Thấp'), ('NORMAL', 'Bình thường'), ('HIGH', 'Cao'), ('URGENT', 'Gấp')], default='NORMAL', max_length=6, verbose_name='Mức ưu tiên'),
        ),
        migrations.AlterField(
            model_name='task',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Để trống nếu là việc chung của CLB.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.event', verbose_name='Sự kiện'),
        ),
    ]
