# Generated by Django 5.2.17 on 2026-10-02 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizing', '0003_task_general_priority_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Đã nhắc sắp đến hạn'),
        ),
        migrations.AddField(
            model_name='task',
            name='overdue_reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Đã báo quá hạn'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Tên ban')),
                ('slug', models.SlugField(help_text='Chữ không dấu, nối bằng gạch ngang. Vd: truyen-thong', max_length=80, unique=True, verbose_name='Đường dẫn')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Giới thiệu ngắn')),
                ('icon', models.CharField(default='bi-people', help_text='Tên icon Bootstrap Icons, vd bi-megaphone', max_length=40, verbose_name='Icon')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_departments', to=settings.AUTH_USER_MODEL, verbose_name='Trưởng ban')),
                ('members', models.ManyToManyField(blank=True, related_name='departments', to=settings.AUTH_USER_MODEL, verbose_name='Thành viên')),
            ],
            options={
                'verbose_name': 'Ban',
                'verbose_name_plural': 'Các ban',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Giao cho cả Ban; để trống người phụ trách thì thành viên Ban tự nhận.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='organizing.department', verbose_name='Ban phụ trách'),
        ),
    ]
