# Generated by Django 5.2.17 on 2026-09-29 03:03

import django.db.models.deletion
import registrations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        default=registrations.models.make_ticket_code,
                        max_length=12,
                        unique=True,
                        verbose_name="Mã vé",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ thanh toán"),
                            ("CONFIRMED", "Đã xác nhận"),
                            ("CHECKED_IN", "Đã check-in"),
                            ("CANCELLED", "Đã huỷ"),
                        ],
                        default="PENDING",
                        max_length=11,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Giá lúc đặt (VNĐ)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày đặt"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Xác nhận lúc"
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check-in lúc"
                    ),
                ),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkins_done",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người check-in",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="events.event",
                        verbose_name="Sự kiện",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="events.tickettype",
                        verbose_name="Loại vé",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người đăng ký",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vé",
                "verbose_name_plural": "Vé",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "status"],
                        name="registratio_event_i_01ddc1_idx",
                    )
                ],
            },
        ),
    ]
