# Generated by Django 5.2.17 on 2026-09-30 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_budget_event_category_event_ends_at_and_more'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking_ref',
            field=models.CharField(blank=True, db_index=True, max_length=8, verbose_name='Mã giao dịch'),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Đang chờ'), ('PROMOTED', 'Đã có vé'), ('SKIPPED', 'Bỏ qua'), ('CANCELLED', 'Đã rời'), ('EXPIRED', 'Hết hạn')], default='WAITING', max_length=10, verbose_name='Trạng thái')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vào hàng lúc')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc lúc')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entry', to='registrations.ticket', verbose_name='Vé được cấp')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='events.tickettype', verbose_name='Loại vé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL, verbose_name='Người chờ')),
            ],
            options={
                'verbose_name': 'Lượt chờ',
                'verbose_name_plural': 'Danh sách chờ',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
