# Generated by Django 5.2.17 on 2026-10-02 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_fill_booking_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_code', models.CharField(db_index=True, max_length=12, verbose_name='Mã vé cũ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Chuyển lúc')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_given', to=settings.AUTH_USER_MODEL, verbose_name='Người chuyển')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='registrations.ticket', verbose_name='Vé')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_received', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Chuyển nhượng vé',
                'verbose_name_plural': 'Chuyển nhượng vé',
                'ordering': ['-created_at'],
            },
        ),
    ]
