# Generated by Django 5.2.17 on 2026-09-30 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TICKET_OK', 'Vé đã xác nhận'), ('TICKET_PEND', 'Vé chờ thanh toán'), ('TICKET_EXP', 'Vé hết hạn thanh toán'), ('EVENT_CXL', 'Sự kiện bị huỷ'), ('REMINDER', 'Nhắc lịch'), ('WAIT_OK', 'Có vé từ danh sách chờ'), ('TASK', 'Được giao việc')], max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
