# Generated by Django 5.2.17 on 2026-09-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thông báo', 'verbose_name_plural': 'Thông báo'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('TICKET_OK', 'Vé đã xác nhận'), ('TICKET_PEND', 'Vé chờ thanh toán'), ('TICKET_EXP', 'Vé hết hạn thanh toán'), ('EVENT_CXL', 'Sự kiện bị huỷ'), ('REMINDER', 'Nhắc lịch'), ('WAIT_OK', 'Có vé từ danh sách chờ'), ('WAIT_EXP', 'Danh sách chờ kết thúc'), ('TASK', 'Được giao việc')], max_length=12),
        ),
    ]
