# Generated by Django 5.2.17 on 2026-10-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('TICKET_OK', 'Vé đã xác nhận'), ('TICKET_PEND', 'Vé chờ thanh toán'), ('TICKET_EXP', 'Vé hết hạn thanh toán'), ('EVENT_CXL', 'Sự kiện bị huỷ'), ('REMINDER', 'Nhắc lịch'), ('WAIT_OK', 'Có vé từ danh sách chờ'), ('WAIT_EXP', 'Danh sách chờ kết thúc'), ('TASK', 'Được giao việc'), ('TASK_DUE', 'Nhắc hạn công việc'), ('APPLY', 'Kết quả ứng tuyển'), ('TICKET_TRF', 'Chuyển nhượng vé')], max_length=12),
        ),
    ]
